ALTER TABLE tickets ADD COLUMN IF NOT EXISTS rma_number VARCHAR(100);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS rma_ref_number VARCHAR(100);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS rma_status VARCHAR(30);
