appname = PhoenixLab
httpport = 8080
runmode = dev
autorender = true
copyrequestbody = true
sessionon = true
sessionprovider = memory
sessionname = phoenixlab_session
sessiongcmaxlifetime = 86400
sessioncookielifetime = 86400
sessionautosetcookie = true

[dev]
dbdriver = postgres
dbconn = host=localhost port=5432 user=tracker password=secret dbname=phoenixlab sslmode=disable

[prod]
dbdriver = postgres
dbconn = ${DATABASE_URL}
